#%RAML 1.0 Trait

headers:
  x-transaction-id:
    description: A unique transaction id used to correlate api requests end to end.
    type: string
    required: true
    example: "e393ef07-de7d-46c7-b514-27581be526d2"