#%RAML 1.0 Trait

queryParameters:
  state:
    description: backend filter used to return covid case reports by a specific state. (if not state specified, reports for all states are returned.)
    type: string
    required: false
    example: "Texas"